name: Dev workflow

on: 
  workflow_dispatch: 

jobs:
    build:
      runs-on: ubuntu-latest
      environment: Dev      
      steps:
        - name: Env Dev - Job Build - Step 1
          env:
            ENV_NAME: ${{secrets.Environment}}
          run: 
            echo "Retrieving Environment name from secrets..."
            echo $ENV_NAME
          
      
  
